
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    working_dir: /app/frontend
    command: ["serve", "-s", "build"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    working_dir: /app/backend
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]